server:
  port: 8000
spring:
  messages:
    encoding: UTF-8
  redis:
#    host: hadoop1
#    port: 7001
    cluster:
      nodes: 192.168.10.11:7001,192.168.10.11:7002,192.168.10.11:7003
    password:
    database: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 600000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=3000)
hbase:
  zookeeper:
    quorum: hadoop1-1
    port: 2181
