host: 127.0.0.1
server:
  port: 8762
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${host}:8848
  redis:
    host: ${host}
    port: 6379
    password:
    database: 0
  datasource:
    url: jdbc:mysql://${host}/mysql?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 600000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=3000)