host: 127.0.0.1
server:
  port: 8762
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: ${host}:8848
  redis:
    host: ${host}
    port: 6379
    password:
    database: 0

