server:
  port: 8763
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
feign:
  hystrix:
    enabled: true
zuul:
  routes:
    api-provider:
      path: /api-provider/**
      serviceId: nacos-provider
